### ISSUE TITLE
i128 is parsed wrong

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/elio-dao-service#10]
```
soroban contract invoke \
   --id "CAGNQW4HPMOEMMQTTJA2IHHHQRGKIG6SXPOV7USV2563ZGNLT35T3AN7" \
   --source "${SECRET_KEY}" \
   --rpc-url "${RPC_URL}" \
   --network-passphrase "${NETWORK_PASSPHRASE}" \
   -- \
   get_configuration \
   --dao_id "$(echo 'DIV' | xxd -p -c 100)"
```

gives you `1000000000000000000` for the threshold, but `https://service.elio-dao.org/daos/DIV/` says it's 0.

The same happens with balances in the other direction. Looks like an overflow to me.

**Comment by Shirku** [comment]
how is this a bug? it's a new thing introduced here: https://github.com/deep-ink-ventures/elio-dao-protocol/issues/45
@deep-ink-ventures i can't read minds, my man :P
e4c524f0a3173583a4116ac0aacf2a24825b549e
