### ISSUE TITLE
Expose endpoint to update addresses and hashes

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/elio-dao-service#3]
We need an endpoint to update the
- core contract address
- votes contract address
- assets WASM hash

The endpoint should accept `PATCH` requests.
The endpoint should require basic authentication, with the credentials being injected via an environment variable.

Upon updating the values, we might consider wiping the DB.

**Comment by Shirku** [comment]
added `/update-config/ ` route. 
requires envvar `CONFIG_SECRET` to be set + header `Config-Secret`
